### ISSUE TITLE
 not all arguments converted during string formatting

### ISSUE THREAD

**Issue by BaerSy** [arendst/mqtt-mysql#6]
When i tried to run this script in python 2.7.9, i always got the following error. With 2.7.5 it was correct.  Do you know why?

Traceback (most recent call last):
  File "mqtt-mysql.py", line 204, in <module>
    S_UNIQUE = get_setting("unique", F_UNIQUE)
  File "mqtt-mysql.py", line 65, in get_setting
    cur.execute("SELECT state FROM settings WHERE setting = %s", (setting))
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 187, in execute
    query = query % tuple([db.literal(item) for item in args])
TypeError: not all arguments converted during string formatting

**Comment by arendst** [comment]
Bob, I Haven't been using these scripts for over a year but I suppose something changed between Python 2.7.5 and 2.7.9 ;-)

Perhaps the Python version changelog explains the difference although the problem seems to be within the MySQLdb plugin.

**Comment by branati** [comment]
Friend, i have a same problem. You fix a big for 2.7.9 version? Tank you

**Comment by jeanpmichel** [comment]
SOLVED, Line 63, change (setting) to [setting].

**Comment by Devanshi1500** [comment]
Thank you jeanpmichel. But, what exactly was causing that error?
